os: linux
dist: xenial
language: python
python:
- '3.6'
- '3.7'
- '3.8-dev'

install:
- pip install -r requirements.txt
- make install
- pip freeze

env:
  global:
  - secure: dBYgTCnJkuOThBLEywObTchqJSR0mjO+IahA7OaMecUqVLQz+SXGVf5PNo67Gxmq/csAt+FGgOL3+PSWYHYdkvt62K2wPIXC4Q8zNyP9iVRmN5oBoEEIUMLCmRbRyu4+q8tmZNbldlgvOW3A+7jre+0b3ZQ0haaHOSgiYlpDfEgvBag9UfD/+9KenbmQJlYXEHM3vZMzMu1OEfljOTsbZW4pYea1nbAye/7VgMBt6bvigs7FzTE4LDMmtpc8pQhKH1N4IaeL0cFuhLGY2f7z3zoy0DvxZ4348WPVWfxsVsRs2+SjA9dtJRz9q1nSTZeM+vMdHkbjtyhTIAK5Edk+c0R5Fb+WvFW8NMFnbDSXDkUjUbWzNMY+/cp3thD8MkhzSrYc0jZl1u0LNZMNqTClUMNw54VzosjMsGqha7Td5jyjs9/8Sak+FqeFpB5SEITUUAcsrdBKlbgjJdoM9HrlEMDErTSoT/mDRre+YBxWkoauCSC4t7vN3bVeFKUKHLTa9ydj4NQ5nOlmaUysAk7zSBp6UVkPw1BrA/kKeboBkj/ugOABBVVuwOJoAMdsCvLlZpNtLtUpmsOuuN0yfp4323V+8X7/jhrqi+Rrhn4lVuwcvZMDxzV1eL+omMlVRlSsd0UK6w6oW/eqTdTiyCwkQjWR3pqcqUQFaGzDUyOcA3g=

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
- make lint
- make mypy
- make test

after_success:
- ls -ltha
- bash <(curl -s https://codecov.io/bash)
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

jobs:
  allow_failures:
  - python: 3.8-dev
  include:
  - stage: build
    name: PyPI Build and Push
    if: type = push AND (branch = master OR tag IS present)
    python: 3.7
    script:
      - make build
      - ls -ltha dist
    deploy:
      provider: pypi
      skip_cleanup: true
      user: pilosus
      password:
        secure: cdMwIx/aVR8YnjZs0aK7zYG5T52ViHbRjuevrGGDJHMnMxNwQ1HqdCwFQOoPkSmjlHnKX65tn/20nFnGGfxs9EEzLzOXyxOEF7k6bwnSdZOZKhOJBbyzdysGT1P86WkGQpjkvrZHLPyTNPEHXHyW9SLtji9w9iqz0bLsCsz2te0dREii0lN6t2s3ZO93mSt/P62uLdP1C9XlLEljN826jXVpMWaUK0P80+yJpqrw3L/HACedD69QqjmgKXr8zngIQgyv8CZKKKdZe6fYhie4SGHSnhh5+wZsc5ML9JqCzA7rl2oYqQJ65PyN47LCvCe5ynxIfRTXpKaP6BDqx845bvMP9cIolSpT1baxM8OsUYX2B2cdTPSmCgoAeWWfNp4yX+44FxQEMxRgNkP2E03aBZdBCG/IR+UhUQUS3buQsJYDYBHhjqZX7NC0h4TL8cGca3r46IwDOIzTNpQ8DZsoEcYg+hpOBrrTCJXamGektO1gt0Ts7qG0JHwXC0GwZiw5+cpZgJV+Y1dVmIe9tIyQ+69k25iLuLnfsUdDp7QRMTaDFfGYrZrEa6ni2bYZ755K87mqNoUZdeRgBavCkhtFhvndgO/81jMQkUDkuZIFkOF5H/X7ohulrgF/EVILp2PYqeEOUFdNqynXDvwJ9u5l3HBU1rjbHniEmzQY1DX2Uc0=
      on:
        tags: true
        all_branches: true
