name: pull_request

on:
  pull_request:
    branches:
    - "*"

jobs:
  license_check:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    - name: Check Python deps licenses
      uses: pilosus/action-pip-license-checker@v0.1.0
      with:
        requirements: 'requirements.txt'
        fail: 'Permissive'
        exclude: 'ipython.*'
        with-totals: true
        table-headers: true
