name: pull_request

on:
  pull_request:
    branches:
    - "*"

jobs:
  lint_and_test:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v.2.2.1
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run linters
      run: make lint
    - name: Run mypy
      run: make mypy
    - name: Run tests
      run: make test


  license_check:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    - name: Check Python deps licenses
      uses: pilosus/action-pip-license-checker@v0.1.0
      with:
        requirements: 'requirements.txt'
        fail: 'Other'
        exclude: 'ipython.*'
        with-totals: true
        table-headers: true
